---
##### role geerlingguy.docker
docker_users:
  - "{{ ansible_user_id }}"

##### role gantsign.sdkman
sdkman_users:
  - "{{ ansible_user_id }}"

##### role homebrew
homebrew_taps:
  - homebrew/core
  - aws/tap
homebrew_installed_packages:
  - aws-sam-cli
  - aws-vault
  - awscli
  - awslogs
  - bzip2
  - docker-compose
  - envoy
  - geckodriver
  - git-cliff
  - git-extras
  - git-flow
  - git-lfs
  - git-now
  - gitleaks
  - go
  - gopls
  - helm
  - ipcalc
  - iperf3
  - iputils
  - isl
  - jq
  - jsonnet
  - k9s
  - kubectx
  - kubeseal
  - kustomize
  - mkcert
  - mongosh
  - nvm
  - protobuf
  - pyenv
  - rcm
  - skaffold
  - skopeo
  - terraform-inventory
  - tfenv
  - traefik
  - unzip
  - wget
  - yq
  - zip

##### dotfiles
dotfiles_repo:
  url: https://github.com/thoughtbot/dotfiles.git
  version: main
  accept_hostkey: false

##### role: unarchive_packages
unarchive_packages:
  - package_binary_dir: "{{ ansible_env.HOME }}/.local/lib/openshift-v4/clients/ocp/4.12.0/openshift-client"
    package_archive: openshift-client-linux-4.12.0.tar.gz
    package_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.12.0/openshift-client-linux-4.12.0.tar.gz
    package_checksum: sha256:4523129522a89cc2c0d18e4e4c794b2409ec67b465de378616902dcacfc27860
    exclude: []
    force_install: false
    link_dir: "{{ ansible_env.HOME }}/.local/bin"
    package_bins:
      - kubectl
      - oc

##### role: flatpaks
flatpak_packages:
  - com.calibre_ebook.calibre
  - com.google.Chrome
  - com.sublimemerge.App
  - com.visualstudio.code
  - org.remmina.Remmina

##### tigervnc
tigervnc_username: "{{ ansible_user_id }}"
tigervnc_groupname: "{{ ansible_user_id }}"

# Connecting to tigervnc-server requires a password.
tigervnc_password: vncpass

# Use existing user's vnc paswword
tigervnc_user_exists: false

# Desktop session xstartup should connect to e.g. gnome-session, mate-session
tigervnc_desktop_session: gnome-session
# test: ssh -v -C -L 5901:localhost:5901 admin@10.0.15.87
