- name: Play for creating a linux devbox
  hosts:
    - devbox-gui
  connection: local
  become: false
  vars_files:
    - default.config.yaml
  roles:
    - role: bootstrap-os
    - role: homebrew
    - role: dotfiles
    - role: unarchive-packages
  tasks:
    - include_role: { name: "tilix" }
      when: is_gnome
    - include_role: { name: "geerlingguy.docker" }
      when: is_docker
      args:
        apply:
          become: true
