---
- name: GNOME | Ensure dconf requirements is installed
  become: true
  ansible.builtin.package:
    name:
      - python3-psutil
      - dconf
      - dbus-tools
      - dbus-daemon
      - gnome-tweak-tool
      - gnome-shell-extension-workspace-indicator
    state: present

- name: GNOME | Disable desktop effects in GNOME
  dconf:
    key: "/org/gnome/desktop/interface/enable-animations"
    value: "false"
    state: present

- name: GNOME | Configure available keyboard layouts in GNOME
  dconf:
    key: "/org/gnome/desktop/input-sources/sources"
    value: "[('xkb', 'us'), ('ibus', 'm17n:vi:telex')]"
    state: present

- name: GNOME | file browser shortcut
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/home"
    value: "['<Super>e']"

- name: GNOME | web browser shortcut
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/www"
    value: "['<Super>w']"

# ###############################################################################
# # Custom shortcuts are more complicated. For each shortcut, you have to
# # define a name, a command, and a binding.
# ###############################################################################

- name: GNOME | tilix | shortcut name
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
    value: "'tilix'"
- name: GNOME | tilix | shortcut command
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
    value: "'/usr/bin/tilix'"
- name: GNOME | tilix | shortcut binding
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
    value: "'<Super>r'"

- name: GNOME | tilix | quake shortcut name
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name"
    value: "'tilix-quake'"
- name: GNOME | tilix | quake shortcut command
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command"
    value: "'/usr/bin/tilix --quake'"
- name: GNOME | tilix | quake shortcut binding
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding"
    value: "'<Super>q'"

# All of your custom shortcuts must also be added to an array.
- name: GNOME | enable custom keybindings
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']"

###############################################################################
# date and time
###############################################################################

- name: GNOME | automatic timezone
  dconf:
    key: "/org/gnome/desktop/datetime/automatic-timezone"
    value: "true"
- name: GNOME | clock show date
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-date"
    value: "true"
- name: GNOME | clock format
  dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'24h'"

# ###############################################################################
# # behavior #
# ###############################################################################

- name: GNOME | workspaces span displays
  dconf:
    key: "/org/gnome/mutter/workspaces-only-on-primary"
    value: "false"

- name: GNOME | app-switcher on the current workspace only
  dconf:
    key: "/org/gnome/shell/app-switcher/current-workspace-only"
    value: "true"

# # - name: set xkb options
# #   dconf:
# #     key: "/org/gnome/desktop/input-sources/xkb-options"
# #     value: "['caps:escape', 'lv3:rwin_switch', 'shift:both_capslock_cancel']"

- name: GNOME | automount
  dconf:
    key: "/org/gnome/desktop/media-handling/automount"
    value: "false"

- name: GNOME | disable hot corner
  dconf:
    key: "/org/gnome/desktop/interface/enable-hot-corners"
    value: "false"
